# Generated by Django 4.0.1 on 2022-02-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profanity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profanity',
            name='value',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profanity',
            name='final',
            field=models.CharField(max_length=1000000),
        ),
    ]
